services:
  # 1. Django Application 
  web:
    build: .
    container_name: task_manager_web
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    env_file:
      - .env_db
    depends_on:
      - db

  # 2. MySQL Database
  db:
    image: mysql:8.0
    container_name: task_manager_db
    restart: always
    env_file:
      - .env_db # Use the same credentials file
    ports:
      - '3307:3306' # Host:3307 -> Container:3306 (For Adminer/Local Tools)
    volumes:
      - db_data:/var/lib/mysql

  # 3. Adminer UI
  adminer:
    image: adminer
    container_name: task_manager_adminer
    restart: always
    ports:
      - '8081:8080'
    depends_on:
      - db

volumes:
  db_data:
